"""update user table

Revision ID: 77086462b967
Revises: 7c6942a23918
Create Date: 2019-01-15 12:12:01.701704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77086462b967'
down_revision = '7c6942a23918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
